# Gmu Theme file
FormatVersion=2

Font1Size=12
Font1Type=truetype
Font1=NotoSans-Regular.ttf
# In case of a true type font, this is an average character width, used
# for positioning of textual elements:
Font1CharWidth=6
#Font1CharHeight=7

Font2Size=12
Font2Type=truetype
Font2=NotoSans-Regular.ttf
Font2CharWidth=6
#Font2CharHeight=7
Font2Color=#3e76ff

Icon.ArrowUp=arrow-up.png
Icon.ArrowDown=arrow-down.png

Header.ImagePrefix=footer
Header.PosX1=0
Header.PosY1=38
Header.PosX2=0
Header.PosY2=64

ListView.ImagePrefix=textarea
ListView.PosX1=0
ListView.PosY1=65
ListView.PosX2=0
ListView.PosY2=-26

Footer.ImagePrefix=footer
Footer.PosX1=0
Footer.PosY1=-26
Footer.PosX2=0
Footer.PosY2=0

Display.ImagePrefix=display
Display.PosX1=0
Display.PosY1=0
Display.PosX2=0
Display.PosY2=38

#Display.Fontsize=12
Display.FontType=bitmap
Display.Font=letters_lcd_2.png
Display.FontCharWidth=10
Display.FontCharHeight=14

Display.FontUpperCaseOnly=yes

Display.Symbols=symbols.png
Display.SymbolsWidth=16
Display.SymbolsHeight=16
Display.Symbol.Play.OffsetX=0
Display.Symbol.Play.OffsetY=2
Display.Symbol.Pause.OffsetX=13
Display.Symbol.Pause.OffsetY=2
Display.Symbol.Stereo.OffsetX=6
Display.Symbol.Stereo.OffsetY=20

Display.TitleScrollerOffsetY=4
Display.TitleScrollerOffsetX1=28
Display.TitleScrollerOffsetX2=-5
Display.PlayPauseOffsetX=5
Display.PlayPauseOffsetY=3
Display.VolumeOffsetX=3
Display.VolumeOffsetY=20
Display.BitrateOffsetX=26
Display.BitrateOffsetY=21
Display.FrequencyOffsetX=136
Display.FrequencyOffsetY=21
Display.TimeOffsetX=248
Display.TimeOffsetY=21
